config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products, only: [:index, :show] do
    resources :offers, only: [:new, :create] do
      post 'reject', to: 'offers#reject'
    end
  end
  
end

app/models/offer.rb
class Offer < ActiveRecord::Base
    validates :shop_name, :price_in_cents, :shipping_price_in_cents, :address, presence: true
    belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
    validates :name, :price_in_cents, :brand, :model, :address, presence: true
    belongs_to :shop
    has_many :offers, dependent: :destroy
end

app/models/shop.rb
class Shop < ActiveRecord::Base
    validates :name, presence: true
    has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  
  def new
    @product = shop.products.find(params[:product_id])
    @offer = @product.offers.new
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

  def create
    product = shop.products.find(params[:product_id])
    offer = product.offers.new(permitted_params)
    offer.shop_name = shop.name
    if offer.valid?
      offer.save
      redirect_to product_path(product.id)
    else
      render 'new'
    end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

  def reject
    product = shop.products.find(params[:product_id])
    offer = product.offers.find(params[:offer_id])
    offer.rejected = !offer.rejected
    if offer.save!
      render json: {status: :ok, rejected: offer.rejected}
    else
      render json: {status: :error, msg: 'Something went wrong'}
    end
    rescue ActiveRecord::RecordNotFound
      render json: {status: :error, msg: 'Something went wrong'}
  end

  private

  def shop
    Shop.last
  end

  def permitted_params
    params.require(:offer).permit(:price_in_cents, :shipping_price_in_cents, :address)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    products = shop.products
    @view = ProductsPresenter.new(products)
  end

  def show
    product = shop.products.find(params[:id])
    @view = ProductPresenter.new(product)
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

  private

  def shop
    Shop.last
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZadanieShops</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/new.html.slim
a.btn(href=product_path(@product.id)) << Back
h1 New offer
.container
    .form-cnt
        = simple_form_for @offer, url: product_offers_path do |f|
            = f.input :price_in_cents
            = f.input :shipping_price_in_cents
            = f.input :address
            = f.button :submit

app/views/products/index.html.slim
h1 Products
.container
    ul#products
        - @view.products.each do |product|
            a.product-link(href=product_path(product[:id]))
                li.product
                    .product-name  =product[:name]
                    .product-price =product[:human_price]
                    .product-brand =product[:brand]
                    .product-model =product[:model]

app/views/products/show.html.slim
a.btn(href=root_path) << Back
h1 Product
.product
    .product-name    =@view.product[:name]
    .product-price   =@view.product[:human_price]
    .product-brand   =@view.product[:brand]
    .product-model   =@view.product[:model]
    .product-address =@view.product[:address]

h2 Offers
a.btn(href=new_product_offer_path(@view.product[:id])) Add offer
- if @view.offers.any?
    ul#offers
        - @view.offers.each do |offer|
            li.offer(data-reject-url=product_offer_reject_path(@view.product[:id], offer[:id]))
                .offer-price          
                    | Price: 
                    =offer[:human_price]
                .offer-shipping-price 
                    | Shipping price: 
                    =offer[:human_shipping_price]
                .offer-address
                    | Address: 
                    =offer[:address]
                .offer-rejected
                    | Rejected: 
                    span.rejected-status=offer[:human_rejected]
                .offer-actions
                    .btn.btn-change-rejected-status
                        - if offer[:rejected]
                            | Recover
                        - else
                            | Reject
- else
    .no-offers-message-cnt
        .no-offers-message
            | There is no offers yet